version: '3'
services:
  dalybms-python:
    container_name: dalybms-python
    image: jayge91/dalybms-python
    devices:
      - /dev/ttyS1:/dev/ttyS1
    cap_add:
      SYS_TTY_CONFIG
    # privileged: true
    environment:
      DEVICE: /dev/ttyS1
      MQTT_SERVER: core-mosquitto
      MQTT_USER: mqtt
      MQTT_PASS: mqtt
      MQTT_CLIENT_ID: dalybms
      MQTT_DISCOVERY_PREFIX: homeassistant
      DEVICE_ID: Daly-Smart-BMS
    restart: on-failure:3
    network_mode: host
      
